	INSERT INTO users (mail, password) VALUES ("admin@test.ch","8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918");
insert into exercises (name, description, reps, sets, users_user_id) values ('Omba', 'Dilation of intestine', 1, 1, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Eimbee', 'Ext audit canal reconstr', 2, 2, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Browsebug', 'Chng hnd mus/ten lng NEC', 3, 3, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Blogtag', 'Pancreat transplant NOS', 4, 4, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Youspan', 'Bilateral vulvectomy', 5, 5, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Realcube', 'Audiological evaluation', 6, 6, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Livetube', 'Vitreous operation NEC', 7, 7, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Leexo', 'Hand & finger arthroscop', 8, 8, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Livepath', 'Jt structur division NOS', 9, 9, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Zoonder', 'Incis cx to assist deliv', 10, 10, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Eare', 'Suture of tongue lacerat', 11, 11, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Meejo', 'Suture hand muscle/fasc', 12, 12, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Pixoboo', 'Mandibular reconst NEC', 13, 13, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Podcat', 'Dental operation NEC', 14, 14, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Skipstorm', 'Gb-to-hepat duct anast', 15, 15, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Realpoint', 'Parasitology-integument', 16, 16, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Tazzy', 'Occupational therapy', 17, 17, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Skipfire', 'Lid reconstruction NOS', 18, 18, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Dynava', 'Serum transfusion NEC', 19, 19, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Oodoo', 'Cervical spine x-ray NEC', 20, 20, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Twimm', 'Pharyngeal repair NEC', 21, 21, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Mycat', 'Video/radio eeg monitor', 22, 22, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Mymm', 'Portal contr phlebogram', 23, 23, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Brightdog', 'Retroperiton pneumogram', 24, 24, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Dabvine', 'Amputat through malleoli', 25, 25, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Browsecat', 'Speech defect training', 26, 26, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Skiptube', 'Sm bowel-rect stump anas', 27, 27, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Fivespan', 'Closed testicular biopsy', 28, 28, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Twiyo', 'Thoracic endarterectomy', 29, 29, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Oyondu', 'Exc max sinus lesion NEC', 30, 30, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Quatz', 'Transplant cadaver donor', 31, 31, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Photobug', 'Rad node dissection NOS', 32, 32, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Oozz', 'Hypnotherapy', 33, 33, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Kwimbee', 'Local perfusion liver', 34, 34, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Camido', 'Implant chemothera agent', 35, 35, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Chatterbridge', 'Pyloromyotomy', 36, 36, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Twiyo', 'Bladder les destruct NEC', 37, 37, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Eadel', 'Sm bowel-rect stump anas', 38, 38, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Browsecat', 'Total exc pituitary NOS', 39, 39, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Ainyx', 'Spinal cord/meninges bx', 40, 40, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Dabfeed', 'Endo emb hd/nk,bare coil', 41, 41, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Voonte', 'Neurectasis', 42, 42, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Fiveclub', 'Dental wiring', 43, 43, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Eare', 'Endosc control gast hem', 44, 44, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Trilia', 'Bone division NEC', 45, 45, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Fatz', 'Rect/perirect dx op NEC', 46, 46, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Dynabox', 'Shorten 1 extraoc musc', 47, 47, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Skiba', 'Cell block/pap-endocrine', 48, 48, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Skidoo', 'Dx ultrasound-digestive', 49, 49, 1);
insert into exercises (name, description, reps, sets, users_user_id) values ('Trudeo', 'Abdominal artery excis', 50, 50, 1);
insert into training_sessions (name, users_user_id) values ('Realfire', 1);
insert into training_sessions (name, users_user_id) values ('Youspan', 1);
insert into training_sessions (name, users_user_id) values ('Zoomzone', 1);
insert into training_sessions (name, users_user_id) values ('Skibox', 1);
insert into training_sessions (name, users_user_id) values ('Babbleopia', 1);
insert into training_sessions (name, users_user_id) values ('Ailane', 1);
insert into training_sessions (name, users_user_id) values ('Skivee', 1);
insert into training_sessions (name, users_user_id) values ('Edgewire', 1);
insert into training_sessions (name, users_user_id) values ('Oozz', 1);
insert into training_sessions (name, users_user_id) values ('Layo', 1);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (9, 46);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (9, 43);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (6, 18);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (5, 38);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (5, 34);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (2, 40);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (10, 3);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (9, 14);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (10, 36);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (1, 48);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (9, 35);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (2, 44);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (5, 29);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (10, 6);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (6, 26);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (7, 42);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (4, 33);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (4, 23);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (6, 12);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (10, 37);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (10, 47);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (9, 30);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (5, 27);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (9, 25);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (7, 9);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (9, 42);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (4, 11);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (7, 17);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (6, 2);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (8, 13);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (6, 4);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (3, 1);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (6, 37);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (10, 7);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (8, 11);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (9, 33);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (8, 32);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (9, 6);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (7, 12);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (6, 11);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (9, 31);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (8, 36);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (6, 10);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (1, 49);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (10, 22);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (10, 4);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (5, 40);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (8, 44);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (3, 43);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (10, 46);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (3, 22);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (7, 10);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (3, 46);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (7, 23);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (1, 33);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (9, 49);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (6, 38);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (2, 6);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (5, 26);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (8, 48);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (8, 21);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (3, 26);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (3, 6);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (7, 26);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (8, 12);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (8, 22);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (1, 42);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (9, 36);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (2, 12);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (4, 18);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (7, 45);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (2, 29);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (2, 48);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (2, 17);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (2, 47);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (4, 46);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (2, 45);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (3, 7);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (5, 42);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (10, 17);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (9, 40);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (9, 37);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (2, 28);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (4, 14);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (4, 15);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (4, 17);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (1, 39);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (4, 3);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (5, 11);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (8, 3);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (8, 5);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (7, 21);
insert into training_sessions_group_exercises (training_sessions_training_session_id, exercises_exercise_id) values (1, 25);
INSERT INTO users_sessions (token, end_date, users_user_id) VALUES ("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYWlsIjoiYWRtaW5AdGVzdC5jaCIsInVzZXJfaWQiOjEsImNyZWF0ZWRfYXQiOiIyMDIzLTA1LTExVDEwOjI0OjU1KzAyOjAwIiwiaWF0IjoxNjgzNzkzNDk1fQ.DooNxNMvt818aibTYOOXBrKjbLhtXlqj1l3wB_B18wY","2025-06-11T11:08:14+02:00", 1);

